### ISSUE TITLE
[Translatable][MongoDB] Error creating or updating translation when field is null

### ISSUE THREAD

**Issue by draco1989** [Atlantic18/DoctrineExtensions#1006]
When a Translatable annotated field is set as empty, TranslatableListener processes it and updates the Translation Document with content property as null. When Mongo saves it, omits content field.
When trying to read that field, there is no check that content property is empty, so it drops an error.

ContextErrorException: Notice: Undefined index: content in **/vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/TranslatableListener.php line 464

**Comment by goatherd** [comment]
:+1: can reproduce this with recent 2.4.0 tag.

My Test-Case:

- config: fallback defined to store in document
- 1. add fallback-translation
- 2. add translation for language X
- 3. drop translation for language X
- now the document causes the Exception mentioned above whenever the translation for language X is requested

This however is some trouble as there should be no longer any UI accessible to recover from that - beside removing the document maybe.

It is somewhat tricky to replicate as the default / fallback-language is not effected. Same holds for required form fields as they can not be emptied once set.

**Comment by goatherd** [comment]
It is possible to re-produce with persist_default_translation enabled.

If the translation value is set first and set to `null` later the object is no longer possible to load with the translation.

Translation looks like

```
{
    "_id" : ObjectId("56c0dc9bc99d8cd1118b4568"),
    "locale" : "en",
    "objectClass" : "MyBundle\Document\MyDocument",
    "field" : "description",
    "foreign_key" : "55e7faac89716ed77c8b456f"
}
```

After reviewing the listener the only case for translation deletion is when the related object is removed. This however is not covering optional fields.

This can never effect document removal or insert, only update to `null` for any previously persisted translation.

The problem lies with https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.12/lib/Gedmo/Translatable/TranslatableListener.php#L634 where `$content === null` is allowed for updating / inserting as translation.

This however is not handled by the translation retrieval causing the reported exception.

As for me it is unintuitive to set a null-record for the dropped translation I'd rather have it remove the translation completely if null'ed.

**Comment by goatherd** [comment]
The current position would likely be https://github.com/Atlantic18/DoctrineExtensions/blob/39c925d393a424e5d6da5fbf2808f87657717c8b/lib/Gedmo/Translatable/TranslatableListener.php#L511

**Comment by goatherd** [comment]
To summarise my opinion on this:

- there is an undefined behaviour if the translation is set to `null` at least in ODM causing translated objects to become inaccessible and breaking code execution with the describes exception.
- it is not possible to either remove the translation for a language-field-pair nor is it possible to set a translation to `null` using the repository
- translation removal is not intended at the moment and should be implemented by the user (https://github.com/Atlantic18/DoctrineExtensions/pull/1523#issuecomment-184356468)

My question would be whether the exception itself should be handled (i.e. as non-existing translation) or a translation removal should be properly implemented.

Maybe the documentation should mention that `null` is not intended and removal not implemented.

**Comment by l3pp4rd** [comment]
can this be closed by #1525 ?

**Comment by goatherd** [comment]
The exception is avoided and no further side-effects seen on my side.

Looks completed to me.

**Comment by goatherd** [comment]
#1007 is no longer needed as well.

**Comment by l3pp4rd** [comment]
thanks ;)
