### ISSUE TITLE
Translation translate() persist the sublcass, findTranslations() looks for the parent class!

### ISSUE THREAD

**Issue by gremo** [Atlantic18/DoctrineExtensions#1123]
Inheritance, where annotations are placed only in the subclass:

```php
/**
 * @ORM\Entity()
 * @ORM\Table("holiday_package")
 */
class HolidayPackage extends Page
{
    /**
     * @ORM\Column(name="content", type="text", nullable=true)
     * @Gedmo\Translatable()
     *
     * @var null|string
     */
    private $content;
}
```

When you translate:

```php
$repository->translate($holidayPackage, 'content', 'en', 'Content...');
```
... it will insert `My\Entity\HolidayPackage` as `object_class`  in `ext_translation` table (**correct**).

However when you try to find a translation:

```php
$repository->findTranslation($holidayPackage);
```
... it will look for `My\Entity\Page` (**wrong**).

The problem is in [`TranslationRepository`](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Translatable/Entity/Repository/TranslationRepository.php#L116) class (line 116) where you always look for the superclass:

```php
$entityClass = $wrapped->getMetadata()->rootEntityName;
```

Is this sort of a bug?

**Comment by dt-creasis** [comment]
We are seeing exactly the same issue with class table inheritance.

Saving and loading a translated entity with a query hint uses the child class name, whereas using `findTranslations()` uses the `rootEntityName`.

We can see this was fixed in 6f7e281b9ddceea440039cecd7ebe8b347daf816 in response to #266 but it appears the reverse logic is actually required.

**Comment by CraigMason** [comment]
Seem to have figured it out.

https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Mapping/ExtensionMetadataFactory.php#L88

This line sets the `useObjectClass` only when `$config` evaluates to `TRUE` - which will not happen if there are no translatable fields. I don't know why this happens as I don't know enough about this library.

Changing `findTranslations()` to use the same `useObjectClass` as the `ExtensionMetadataFactory` fixes the issue.

Will create a PR - however, I'm not sure why the 'base' class isn't a candidate for the `useObjectClass` if there are no fields. If any fields are added later to the base class, all of the 'class' entries in 'ext_translations' will be incorrect.

**Comment by l3pp4rd** [comment]
Hi, this is a complicated issue because of inheritance. I agree that this might not be correct at the moment, in current implementation both solutions will be with issues. Not sure when I would be able to have willing and time to look into this for ways to solve inheritance and extended class issues.. Before that there were only mapped super classes, now class extensions also are working in ORM and brought these problems

**Comment by CraigMason** [comment]
As me and @dt-creasis were discussing earlier, one of the problems is when a field is added, you will need a migration + post-up to update all of your `Class` entries - but one also needs to know what the target class should be.

I don't know enough about this Translatable helper to suggest a solution. But thank you for the project - we use it extensively.
