### ISSUE TITLE
[Sluggable] Relation targeting a slugged identifier does not work 

### ISSUE THREAD

**Issue by rolebi** [Atlantic18/DoctrineExtensions#1349]
Hi,

I end up having `__id__` as `Comment.post_slug` values using this mapping.

Any hint ? (test available [here](https://github.com/rolebi/DoctrineExtensions/tree/fix-multicolum-relation-slugs))

```php
/**
 * @ORM\Entity
 */
class Post
{
    /**
     * @ORM\Column(name="title", unique=true, length=64)
     */
    private $title;

    /**
     * @ORM\Id
     * @Gedmo\Slug(unique=true, fields={"title"})
     * @ORM\Column(length=64, nullable=false)
     */
    private $slug;
}

/**
 * @ORM\Entity
 */
class Comment
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Post", inversedBy="comments")
     * @ORM\JoinColumn(name="post_slug", referencedColumnName="slug", nullable=false)
     */
    private $post;
}
```

**Comment by l3pp4rd** [comment]
well, yes, slug cannot be generated as identifier because orm requires id on persist, if we handle slug on persist, there are numerous other bugs. the situation now allow less wtf factors.. for instance you may persist the entity before setting title, the event will be fired only once, the time it was first persisted. you may change the title after persisting or slug may change during flush based on unique index. if you want something working the way you want, create it for your use case, for example generate the slug manually using the transliterator library and uniqueness check.. extensions are for very basic use cases usually ending up in custom solutions

**Comment by rolebi** [comment]
@l3pp4rd actually the identifier generation works well and I end up having the right slug for `Post`.

Nevertheless, if I `persist/flush` a `Post` *then* a `Comment` the slug generated for `Post` is alright but it seems that the one used for the relation with `Comment` and found in the `joinColumn` is not the right one.

**Comment by l3pp4rd** [comment]
ah, haven't looked at the mapping close enough. it is an unusual use case. orm probably tries to set the joincolumn before the slug is generated, would need to update the join column after the slug is available. It will be quite complicated since **Post** will need to track comments inserted. I currently do not use extensions and I doubt if I would find time for this. So if you need such an use case, either update the source code yourself or generate slug manually

**Comment by rolebi** [comment]
Ok, haven't find a way to force `UnitOfWork` to update its list of identifiers per object hash from within the SluggableListener. 

We will stick with the `persist` then `clear` approach to ensure that identifiers associated to object in UOW are the right ones.
