### ISSUE TITLE
Is it possible to get Left and right different for root ?

### ISSUE THREAD

**Issue by quentincurtet** [Atlantic18/DoctrineExtensions#1370]
I would like to have my right border and my left border always different, i explain : 
For my 'parent 1', the borders are 1 and 2, and for my 'parent 2' i would like to have automatically 3 and 4. Is it possible ?

 ![capture d ecran de 2015-07-29 15 41 34](https://cloud.githubusercontent.com/assets/6769513/8958993/817fe490-3608-11e5-8134-b7f173ae805b.png)

And if my 'parent 1' has a child, the borders of parent 1 would be 1 and 4 and the children borders 2 and 3 and 'parent 2' would be 5 and 6.

**Comment by l3pp4rd** [comment]
yes, do not add root column at all.

**Comment by quentincurtet** [comment]
Ok, thank you for your answer.
What is the interest ?
What is the best practice ? Using root or not ?

Thank you.

**Comment by l3pp4rd** [comment]
it depends on your requirements, if for example the project tree is based per company, so one root tree might be based per company. since the tree is not concurrently safe, it might be convenient to lock the company for update before updating or inserting tree node. Otherwise, if your tree is a category tree for products, then there is no point in having root column.
In general, it would be convenient to make root a relation instead and there is a plan to support that one day.. it depends on your requirements, if for example the project tree is based per company, o root tree might be based per company

**Comment by quentincurtet** [comment]
Thank you a lot !
It helps me !
