### ISSUE TITLE
null attribute remains untranslated

### ISSUE THREAD

**Issue by picks44** [Atlantic18/DoctrineExtensions#1437]
Hello,
I have an entity with a nullable "video" attribute.
If the user's locale is different from the default one, articles get automatically "localized" (translated) using
```
if ($this->getUser()->getLocale() != $this->getParameter('locale')) {
    $article->setTranslatableLocale($this->getUser()->getLocale());
}
```
But if the "video" attribute is not originally filled, it is not "translated" into my `article_translations` table.
And then the article is not displayed as the system doesn't find all the translatable fields (video is missing). 
How can I force the null attributes to be "duplicated" into the translations tables ?

**Comment by l3pp4rd** [comment]
well, when you save entity, it must save all field translations. otherwise with a new field migration make translation migration too, by adding translations for that field together with migration. Translatable manages each field translation as a separate row in database, all must be available to translate a record properly. It would be better to store all field translations in single record, but that brings complications, so translatable is what it is now..

**Comment by picks44** [comment]
OK, for now I'll just force the attribute to be set to a 'null' string and will deal with it with Twig.
```
 if ($this->getUser()->getLocale() != $request->getLocale()) {
    if (is_null($article->getVideo())) {
        $article->setVideo('null');
    }
    $article->setTranslatableLocale($this->getUser()->getLocale());
}
```
