### ISSUE TITLE
How to check if record has been translated ?

### ISSUE THREAD

**Issue by picks44** [Atlantic18/DoctrineExtensions#1439]
How can I set a "translated" label to the entity records which have already been translated when displaying them in a list ?
Is there a simple to check if the record has a translation in a given locale ?

**Comment by l3pp4rd** [comment]
this kind of state is not stored anywhere. you can, query the translation entity table to find out which are not translated. if you use personal translations, it would allow more flexibility, since in that case you may check if translation is available in the [translation collection](https://github.com/Atlantic18/DoctrineExtensions/blob/master/example/app/Entity/Category.php#L109)

**Comment by picks44** [comment]
Tell me if I'm wrong, but if I add a property to my Article entity where I record the locales of the translation when they are actually translated ?
```
$em = $this->getDoctrine()->getManager();
$article->setTranslatableLocale($locale);
$article->addTranslation($locale);
$em->persist($article);
$em->flush();
```

**Comment by l3pp4rd** [comment]
you may also issue a query over translation table to get locales, but in general there is no generic implementation out of the box for this functionality.

**Comment by skhattane** [comment]
@l3pp4rd , a more generic question : How can we manage entity translated ?

**My Use Case :**
I have a recipe entity. For now I query the translation entity via a custom repository and use `$query->setHint(TranslatableListener::HINT_INNER_JOIN` true) to retrieve every fully translated recipes in only one locale. (I don' want fallback and I don't want entities not fully translated). It works.

** 3 questions : **
1. Is there a simple way to retrieve entities in specifics locales (not one locale, not all locales, but severals specifics whitout multi-queries)
2. About performance, the way of picks44 seem to be the best and more flexible. The problem is to maintain consistency. What is the best practice and usual strategy ? No feature out of the box ?
3. How can I fetched entities not fully translated (and only this ones) in a specific locale (I develop a translation module for users of my website ) ?

**Comment by l3pp4rd** [comment]
Hi @skhattane it is important to understand that extensions are made for rapid development, they do not need much of configuration and may be hooked at any stage in the project. That is the purpose of extensions so people could easily integrate them. Note, they are not simple, but easy to use and that is the selling point for most of the users.

Extensions are not performance wise and they will never be. Projects needing better performance should implement custom solutions, which would suite specific needs (whether it is performance or functionality based). 

Getting back to the question. You may use personal translation instead so it could have a standard oneToMany collection of translations and that you could join while loading the entity.

**Comment by skhattane** [comment]
@l3pp4rd, thanks for your answer. I understand your point of view. I'll try personal translation and give news if pbl with that.
