### ISSUE TITLE
[loggable] Empty object_id on create rows

### ISSUE THREAD

**Issue by nepda** [Atlantic18/DoctrineExtensions#1440]
Some of my create entity entries don't have an `object_id` (they are `null`-values). One or two rows later, the `LogEntry` for this entity is correctly inserted. I've no clue where to start searching for this error!?

**Comment by l3pp4rd** [comment]
well, is your primary key generated by some kind of event listener? because it seems like it failed to get the primary keys in time.. actually this behavior is hard to guess. since I do not get such issues from users often, I would think that something is different in your context compared to usual.

**Comment by nepda** [comment]
No, the primary key is a simple integer auto generated id. I've a few listeners on this entity and in my `postPersist` there is another `persist` in some cases. Ok, I will debug this and post it here, if I can find anything. Thanks!

**Comment by l3pp4rd** [comment]
if you have a persist in postPersist - extensions won't work. because it will not be able to track entities persisted in post persist. Loggable analyzes entities in onflush event. it would be best for you to use onflush events for your listeners and hook them before extension listeners.

**Comment by nepda** [comment]
Okay, thank you!
