### ISSUE TITLE
loggable logs new values instead of old ones

### ISSUE THREAD

**Issue by hosseinashrafzadeh** [Atlantic18/DoctrineExtensions#1494]
in loggable 
when logs entries the new value is not required but the old ones is required
when inserting new value in db we always have new value but old value should be kept in log
in latest version
in vendor\gedmo\doctrine-extensions\lib\Gedmo\Loggable\LoggableListener
function getObjectChangeSetData 
in line 234
$value = $changes[1];
$value contain new value
and i think it should be
$value = $changes[0];

0: old value
1:new value

**Comment by l3pp4rd** [comment]
if you keep history, that is how it should be from the start. if you insert a record, what should it say? null, null null? what if this record is never updated? If you require older values, then look into previous versions. if you have added loggable to your production project at some point, then you manually need at least set default versions or copy the database to know what was the last version, that is your concern, same as your application

**Comment by hosseinashrafzadeh** [comment]
my English is not good
in current version we log only new ones
without logging created values we lost our history
and loggable is not usable for existing project
and i think restore old data has no mean
i think for new records (create action) we should kept new values and for update action we should kept old values
you can pass action to getObjectChangeSetData as last parameter
so getObjectChangeSetData function is aware of action
so when create new record the function will return new record
and for updated records the function will return old record
so null null null  will solve
and now with delete action we have null null null

**Comment by l3pp4rd** [comment]
well, it is hard to understand what you want to achieve, but my point is that, you cannot just throw in loggable (or any other logging tool) in project and expect to have history for old values, I do not know any existing tool which does that. Because of that, you should use custom solution or from the start of the project, for example for all history I use [audit bundle](https://github.com/DATA-DOG/DataDogAuditBundle) because it logs everything including relation, collection changes. It depends on your client needs. In your place I would not blame some third party project, because you haven't looked into what it logs and what it does and do not blame it here, use what you need and do not waste my time for such responses

**Comment by hosseinashrafzadeh** [comment]
thanks for your valuable time
