### ISSUE TITLE
[Translatable] Objects with lots of translatable fields makes too big queries

### ISSUE THREAD

**Issue by nikophil** [Atlantic18/DoctrineExtensions#1502]
Hello,

i'm experiencing troubles with Translatable on big objects with many translatable fields.
Actually i got an entitty with 50+ fields translatables and putting the Hint sets a Join in the query for each one. So i end up with queries with more than 50 joins. Even if a just need one or two of these fields, and even if i request partials.

Is there any way to lighten these queries, because my db server is running into a lot of slow queries that make it  crash.

thanks for your help and your work, obviously  =)

**Comment by l3pp4rd** [comment]
hi, if you have 50 translated fields, the problem is elsewhere. translatable is meant for small projects (prototypes) to craft something small and functioning. A basic website is fine, with 3 translation fields per entity if needed. But if you are making something so complex, use custom solution or make it simple in the first place. there is nothing to change or improve in extensions, they do what they are meant to.. and they are not performance wise.

**Comment by nikophil** [comment]
hello and thank you for your answer.
That's kind of a bad news for me...
Do you think there's any way to override the TranslationWalker in order to reduce the joins to the list of the fields i am willing to select ?

**Comment by l3pp4rd** [comment]
you can clone extensions and customize it, or copy to your autoload directory and customize the way you like.

**Comment by nikophil** [comment]
well... actually i was asking if this sounds like a good idea  ;)
thanks, btw

**Comment by nikophil** [comment]
I've developped a little light-weight patch that aim to reduce the joins on the set of fields that are in select clause (if defined...)
Do you think i might do a PR ?
IMHO this could improve the prefs of requests...
Thanks for your answer.

**Comment by l3pp4rd** [comment]
no, that is a complex feature, cannot be applied easily on extensions without bugs. because translatable do not need predefined set of fields including joined field tables.. lets leave it as is

**Comment by nikophil** [comment]
Indeed, Translatable does not need predefined set of fields
but why not restraining joins when a set of selected fields exists ?

This is not that complex : 
1 - extract selected fields from SelectStatement
2 - in the for loop in TranslationWalker::prepareTranslatedComponents() check if the current field on the current dqlAlias exists in the selectFieldsSet. If it does't : don't do the join...
3 - In the case when no field is explicitly passed to queryBuilder, nothing changes and the request comes with all joins...

**Comment by l3pp4rd** [comment]
in almost all cases, users select all fields as they map them to objects, the ORM is exactly meant for that. this is the first request, because most of users do not have 50 fields to translate, please use your customization, I do not have time to maintain new features in extensions, this might cause issues for standard use cases..
