### ISSUE TITLE
Bad indexes annotation writing

### ISSUE THREAD

**Issue by Ronan-Lenor** [Atlantic18/DoctrineExtensions#1516]
since i updated my framewok i got a new error.
i couldn't create a databse because of this "object_class" & "foreign_key" as in your exemple

https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/translatable.md#advanced-examples

```
/**
 * @ORM\Table(name="article_translations", indexes={
 *      @ORM\Index(name="article_translation_idx", columns={"locale", "object_class", "field", "foreign_key"})
 * })
 * @ORM\Entity(repositoryClass="Gedmo\Translatable\Entity\Repository\TranslationRepository")
 */
```

to resolve it, i needed to rewrite all my entities with "objectClass" & "foreignKey" where "_" and the first letter of the firld was removed/changed

**Comment by l3pp4rd** [comment]
yes, the documentation will need some updates.

**Comment by stevro** [comment]
This is a BC change for whoever makes an update. Maybe it should be listed somewhere in a changelog or in Translatable docs.

**Comment by l3pp4rd** [comment]
it will be, master branch switched to 2.5.x. I recommend you to have a tag ~2.4.0 in your composer.json. thanks for noting about that ;) If you use underscore [naming strategy](http://stackoverflow.com/questions/12702657/how-to-configure-naming-strategy-in-doctrine-2) that should resolve fine, otherwise you need to name columns based on default naming strategy. To be consistent with this naming strategy extensions do not set explicit column names anymore
