### ISSUE TITLE
[Translatable] Entities are not saved in ext_translation

### ISSUE THREAD

**Issue by cptCAPS** [Atlantic18/DoctrineExtensions#1527]
Hi,
at first i enter content in default language. But when i enter the translation,  some of the "@Gedmo\Translatable" fields in entity have no entry in the translation table and override the default language content.
The strange thing is when i enter at first the translation and secondly enter the default_language everything works fine.

In my example name is not translated.

[Attachment.txt](https://github.com/Atlantic18/DoctrineExtensions/files/132744/Attachment.txt)

**Comment by l3pp4rd** [comment]
Hi, for default locale translations extension does not create a record, since these fields are already available in the entity, for any other language it will create a record in the table separately. If you wish to force all translations to be persisted including default locale, there is an [option in listener](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Translatable/TranslatableListener.php#L105) you should set it to true for this reason.
