### ISSUE TITLE
generate slug for entity if specific symbol

### ISSUE THREAD

**Issue by shubaivan** [Atlantic18/DoctrineExtensions#1553]
I have entity skill and have field slug from field skill and when I create skill and write C++ have slug=c OR if create C. - have slug=c OR when create C# still have slug=c. I think in Gedmo have something regular expression. Maybe who know how overwrite Gedmo slug or hot to fix this problem ?

    use Gedmo\Mapping\Annotation as Gedmo;

    /**
     * Skills.
     *
     * @ORM\Table(name="code_directory_skills")
     */
     class Skill
     {
    use Timestampable;
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Expose()
     * @Groups({"for_skill_by_id", "for_all_skills", "for_all_skills_extended"})
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="skill", type="string", length=255)
     * @Expose()
     * @Groups({"for_skill_by_id", "for_all_skills", "for_all_skills_extended"})
     */
    private $skill;

    /**
     * @Gedmo\Slug(fields={"skill"}, updatable=true)
     * @ORM\Column(name="slug", type="string", nullable=false)
     * @Groups({"for_skill_by_id", "for_all_skills", "for_all_skills_extended"})
     * @Expose()
     */
    protected $slug;

I create listener

    namespace Artel\ProfileBundle\Listener;

    use Gedmo\Sluggable\SluggableListener as BaseSluggableListener;

    class SluggableListener extends BaseSluggableListener
    {
    public function __construct()
    {
        $this->setTransliterator(array('\Artel\ProfileBundle\Util\Transliterator', 'transliterate'));
    }
    }

and create translator in $text I have C++ then in 

    Urlizer::urlize($text, $separator) //have have C

 
class:

    use Gedmo\Sluggable\Util\Urlizer;

    class Transliterator
    {
    public static function transliterate($text, $separator = '-')
    {
        $text = Urlizer::unaccent($text);
        return Urlizer::urlize($text, $separator);
    }
    }

I change 

    class Transliterator
    {
    public static function transliterate($text, $separator = '-')
    {
        $text = Urlizer::unaccent($text);

        return $text; //have C++
    }
    }

but in DB still have only slug=c

and config this extension:

    stof_doctrine_extensions:
    class:
        sluggable: Artel\ProfileBundle\Listener\SluggableListener
    default_locale: "%locale%"
    orm:
        default:
            timestampable: true
            sluggable:     true
            softdeleteable: true

How in Transliterator enable specific symbol for sluggable ?

**Comment by l3pp4rd** [comment]
hi, you can change transliterator for sluggable to any callable function and adapt it whatever way you like, like changing + sign to **plus** word and # sign to **sharp** word. Sluggable does not have these kinds of replacements by default, because it does not know your underlying business logic. It was created to transliterate sentences and create url friendly slugs by default

**Comment by l3pp4rd** [comment]
stof bundle makes listeners private I think and hides away much of the options. My advice is to use [symfony2 manual for extensions](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/symfony2.md) in order to set it up with all options at hand. you can set transliterator directly in the configuration.
