### ISSUE TITLE
Property "root" in "..." was already declared, but it must be declared only once

### ISSUE THREAD

**Issue by dvapelnik** [Atlantic18/DoctrineExtensions#1710]
I'm using man by link https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/tree.md#yaml-mapping and see error
```
[Doctrine\ORM\Mapping\MappingException]                                                                                        
  Property "root" in "AcmeBundle\Entity\Category" was already declared, but it must be declared only once
```
This is very expected behavior

**Comment by franciscomemoli** [comment]
Same problem, some solution or workaround?

**Comment by l3pp4rd** [comment]
do not map it twice, maybe you use annotation mapping + yaml? check metadata drivers registered in orm

**Comment by franciscomemoli** [comment]
Thanks for the replay.
I found my error, and was totally mine.
Also I think that the documentation for yml is wrong (https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/tree.md#yaml-mapping-example), because the root mapping is duplicated in the fields secction and manyToOne
  fields:
    root:
      type: integer
      nullable: true
      gedmo:
        - treeRoot
  manyToOne:
    root:
      targetEntity: Entity\Category
      joinColumn:
        name: tree_root
        referencedColumnName: id
        onDelete: CASCADE
      gedmo:
        - treeRoot

I thinks that the mapping in the fields secction should not be.
