### ISSUE TITLE
[NestedTree] Listener breaks tree when DELETE query is rolled back

### ISSUE THREAD

**Issue by winzou** [Atlantic18/DoctrineExtensions#1745]
Hi,

I'm using `v2.4.26`.

I'm facing an issue. I do a `$em->remove($node)` on one of the nodes of my nested tree. You'll get it viewing the queries:

    UPDATE location SET tree_left = tree_left - 2 WHERE tree_left >= 75 AND tree_root_id = ?
    UPDATE location SET tree_right = tree_right - 2 WHERE tree_right >= 75 AND tree_root_id = ?
    START TRANSACTION
    DELETE FROM location WHERE id = ?
    ROLLBACK

As my `DELETE` statement has failed, the transaction is rolled back. The problem is that the 2 queries that update the tree beforehand (executed by the lib listener) are *outside* of the transaction. Hence they are not rolled back at all and my tree is now corrupted.

I didn't find anything on this. Is this a supported case? What is the best practice to work around this if not supported by the lib?

Thanks a lot!

**Comment by l3pp4rd** [comment]
Hi, in order to ensure data consistency you have to always use pessimistic locking and manually start the transaction see [docs](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/transaction-safety.md#making-safe-transactions-in-concurrent-environment). Otherwise your tree will not be consistent (in concurrent environment) or in your case if something in the middle fails.

**Comment by winzou** [comment]
OK thanks.
