### ISSUE TITLE
Incorrect AbstractAnnotationDriver::getRelatedClassName using

### ISSUE THREAD

**Issue by Cosmologist** [Atlantic18/DoctrineExtensions#1788]
At the Gedmo/Loggable/Mapping/Driver/Annotation:57 - $cl from AbstractAnnotationDriver::getRelatedClassName return value maybe classname, true or false.
But the annotation driver always expects class name.
You should use class_exists instead getRelatedClassName

**Comment by l3pp4rd** [comment]
well, it checks for **class_exists** in that [method](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Mapping/Driver/AbstractAnnotationDriver.php#L103) if it returns empty string, then boolean expression evaluates to false and class is treated as not found. The reason why it is that way, is because it allows to use relative class name, like doctrine ORM allows you to. If the class configured is in the same namespace as mapped class, it will try to append that namespaces to verify it.

**Comment by Cosmologist** [comment]
Yes, I agree with that. 
But what will happen if an interface will passed trough logClassEntry?

**Comment by l3pp4rd** [comment]
well, guess we could add `|| interface_exists($className)` to the last line expression. Now it ends up only supporting relative class names not interfaces. would you open a pull request?

**Comment by Cosmologist** [comment]
Ok.
Can i ask some related questions here, without new issues opening?

**Comment by l3pp4rd** [comment]
sure ;)

**Comment by Cosmologist** [comment]
1. Very strange [check](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Loggable/Mapping/Driver/Annotation.php#L64) - why non-private fields skip if class is MappedSuperclass?
2. Why composite ID field [checks](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Loggable/Mapping/Driver/Annotation.php#L85) only for non MappedSuperclass?

**Comment by l3pp4rd** [comment]
1. all metadata is inherited from mapped super classes, so it is skipped in order to prevent duplicate fields.
2. we cannot support composite keys for loggable classes, because we have a log entry supporting only one foreign key, not more.

**Comment by Cosmologist** [comment]
1. Private modifier used as marker for non-inherited fields?
2. I understand, but you should check composite keys for all classes (mapped superclass and regular)

**Comment by l3pp4rd** [comment]
1. yes exactly, if a property is private, then the metadata will not be visible in extended class. I guess it is strange, but protected or public properties are visible in inherited classes, which would lead to field duplication if we map all these properties. You can test that in order to see.
2. again, we are not interested in mapped superclasses and $meta->identifier will always reflect all primary keys, including ones from super classes.

**Comment by Cosmologist** [comment]
1. ok
2. but we can throw exception early - when process mapped superclass

**Comment by l3pp4rd** [comment]
2. well, that does not count in my opinion as any value

**Comment by Cosmologist** [comment]
Ok, thank you so much
