### ISSUE TITLE
Immutable types are undocumented

### ISSUE THREAD

**Issue by garak** [Atlantic18/DoctrineExtensions#1859]
Types added in 0b7121f8b15596f20284ee3acdf731940f43a831 are not documented.

**Comment by phansys** [comment]
Documentation at commit you're pointing states the following about `SoftDeleteable` annotation: ["It must be of any of the date types"](https://github.com/Atlantic18/DoctrineExtensions/blob/0b7121f8b15596f20284ee3acdf731940f43a831/doc/softdeleteable.md#softdeleteable-entity-example). IMO, there is no documented distinction for a specific date type, so there is no need to make any special distinction about these types (which are provided by `doctrine/dbal` and supported in a transparent way by this library). Otherwise, all supported types should be listed.
