### ISSUE TITLE
doctrine/mongodb-odm 2.0 compatibility

### ISSUE THREAD

**Issue by shadz3rg** [Atlantic18/DoctrineExtensions#2027]
Hello community!
There is upcoming release of new major version of Mongo ODM (which i am forced to use since api-platform supports version 2.0 only).
And sad news: library incompatible. But for now errors is pretty simple, renamed classes, interface declaration, etc.  

What we can do in this situation? Is there active fork or branch for new version?
**Atleast we need to add doctrine/mongodb-odm 2.0 to conflicts section of composer file.**

**Comment by AkenRoberts** [comment]
Hi @shadz3rg, sorry for the lack of attention.

Good points brought up here with the upcoming ODM 2.0 release. I did add the conflict to `composer.json` in d6cecca3570a908faf0890249ccbc11562cef317 so that'll keep some of the hassle down when ODM 2.0 is stable.

Unfortunately there is no real development happening on Doctrine Extensions. I'm basically just keeping the lights on at this point. I'm working on a 3.0 release on `master` simply to bump the minimum PHP version and other dependencies, make testing easier, things of that nature. Once that happens, if myself or anyone else can find the time to really contribute new code (including yourself - PRs welcome!), then maybe ODM 2.0 compatibility can happen then.

I'm going to make an issue now with some overall community updates and an agenda I think can at least move the project forward a bit and get it to a place where updates like these can be more of a reality. Keep an eye for it and share your thoughts.
