### ISSUE TITLE
PHP mapping metadata

### ISSUE THREAD

**Issue by KartaviK** [Atlantic18/DoctrineExtensions#2161]
I'm not actually understand how set up soft deleteable extension on entity with php `ClassMetadata` class. With `addEntityListener`?

**Comment by AkenRoberts** [comment]
If you're asking how to define extension metadata using plain PHP instead of a driver like `Annotations`: it's currently difficult. There is no unified API for extension metadata; it all gets turned into a big associative array that you'd have to piece together by looking at all of the individual extensions' driver implementations. None of which is currently documented.

I'm sorry I can't be of more help than that.

**Comment by KartaviK** [comment]
@AkenRoberts I see a abstract driver in package. It is possible to extend it and make own custom for plan php? And if answer yes what api of ClassMetadata i can use to provide it

**Comment by AkenRoberts** [comment]
`Gedmo\Mapping\Driver\AbstractAnnotationDriver` is specifically for Annotations, and isn't very useful for PHP-based mapping.

And this extensions library does not use Doctrine's `ClassMetadata` at all. The custom metadata for extensions is distilled into a plain array.

**Comment by KartaviK** [comment]
I understand, thx for help)
